[package]
name = "ulog_rs"
version = "0.1.0"
edition = "2021"
publish = false

[profile.dev]
debug = true

[dependencies]
byteorder = "1.5.0"
tempfile = "3.13.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
regex = "1.11.1"
lazy_static = "1.5.0"
csv = "1.3.0"

