[package]
name = "integration_tests"
version = "0.2.2"
edition = "2021"
publish = false

[dependencies]

[dev-dependencies]
yule_log = { path = "../core", features = ["macros"], default-features = false }
